project:
  type: book
  output-dir: "docs"
  execute-dir: "project"
book:
  title: "Equity Action Plans 2023 Keyword Analysis"
  date: today
  chapters:
    - index.qmd
execute:
  eval: true
  echo: false
  freeze: false
  warning: false
  message: false
  keep-md: true
format:
  dashboard:
    theme: styles.scss
    code-fold: true
    code-line-numbers: true
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-depth: 3
    number-sections: false
    number-depth: 3
    knitr:
      opts_chunk:
        dev: "ragg_png"
editor_options:
  chunk_output_type: console
